background-color=#20352bcc
text-color=#e2ebc0

border-color=#7fb39a

[urgency=normal]
border-color=#7fb39a

[urgency=high]
border-color=#d26a6a

[app-name=lightcord]
border-color=#7fb39a

[summary~="log-.*"]
border-color=#7fb39a
