background-color=#242933cc
text-color=#bbc3d4ff

border-color=#5e81ac99

[urgency=normal]
border-color=#5e81acff

[urgency=high]
border-color=#bf616aff

[app-name=lightcord]
border-color=#5e81acff

[summary~="log-.*"]
border-color=#5e81acff
