#!/usr/bin/env bash

choice=$(
printf "Rebuild\nRebuild Boot\nUpgrade\nClean\nNixOS Version" |
fuzzel --dmenu -p "System"
)

case "$choice" in
    "Rebuild")
        ghostty -e rebuild
        ;;
    "Rebuild Boot")
        ghostty -e rebuild-boot
        ;;
    "Upgrade")
        ghostty -e upgrade
        ;;
    "Clean")
        ghostty -e clean
        ;;
    "NixOS Version")
        ghostty -e version
        ;;
esac
