background-color={{background}}cc
text-color={{foreground}}

border-color={{color4}}

[urgency=normal]
border-color={{color4}}

[urgency=high]
border-color={{color1}}

[app-name=lightcord]
border-color={{color4}}

[summary~="log-.*"]
border-color={{color4}}
