# --------------------------------------------------
# Window Sizing
# --------------------------------------------------

autofit=50%x50%

# --------------------------------------------------
# Audio
# --------------------------------------------------

volume=15
volume-max=150

# --------------------------------------------------
# Playback
# --------------------------------------------------

loop-file=inf
loop-playlist=inf

autocreate-playlist=same
directory-mode=ignore

save-position-on-quit=yes
save-watch-history=yes

# --------------------------------------------------
# Performance
# --------------------------------------------------

hwdec=auto-safe

# --------------------------------------------------
# Reset State
# --------------------------------------------------

reset-on-next-file=window-scale,video-zoom,video-rotate,video-align-x,video-align-y,video-aspect-override,video-pan-x,video-pan-y,panscan,vf
