#!/usr/bin/env bash

set -e

gsettings set org.gnome.desktop.interface gtk-theme "Gruvbox-Dark-Hard"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Ice"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

echo vintage > ~/.cache/current-theme
