#!/usr/bin/env bash

set -e

STATE="$HOME/.cache/current-theme"

CURRENT=$(cat "$STATE" 2>/dev/null || echo graphite)

if [[ "$CURRENT" == "graphite" ]]; then
    theme-vintage
    echo vintage > "$STATE"
else
    theme-graphite
    echo graphite > "$STATE"
fi
