# Rainier Fallback Bash Shell

# Aliases
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"

# Smart directory jumping
command -v zoxide >/dev/null && eval "$(zoxide init bash)"

# Prompt Customization
command -v starship >/dev/null && eval "$(starship init bash)"
