"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
$hostname\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$nodejs\
$python\
$rust\
$golang\
$php\
[](fg:color_blue bg:color_purple)\
$nix_shell\
[](fg:color_purple bg:color_bg3)\
$docker_context\
$cmd_duration\
[](fg:color_bg3 bg:color_bg1)\
$status\
$time\
[ ](fg:color_bg1)\
$line_break\
$line_break\
$character"""

palette = 'tokyo_night'

[palettes.tokyo_night]
color_fg0 = '#e3e5e5'
color_bg1 = '#1d2230'
color_bg3 = '#212736'
color_blue = '#212736'
color_aqua = '#394260'
color_green = '#769ff0'
color_orange = '#a3aed2'
color_purple = '#212736'
color_red = '#bf616a'
color_yellow = '#769ff0'

[os]
disabled = false
style = "bg:color_orange fg:#090c0c"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:#090c0c"
style_root = "bg:color_orange fg:#090c0c"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:color_orange fg:#090c0c"
format = '[@ $hostname ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_green bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
staged = "+${count}"
deleted = "✘${count}"
untracked = "?${count}"
format = '[[($all_status$ahead_behind )](fg:color_green bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_green bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_green bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_green bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_green bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_green bg:color_blue)]($style)'

[nix_shell]
symbol = ""
style = "bg:color_purple fg:color_green"
format = '[[ $symbol $name ]($style)]'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_green bg:color_bg3)]($style)'

[cmd_duration]
min_time = 2000
show_milliseconds = false
style = "bg:color_bg3"
format = '[[  $duration ](fg:color_fg0 bg:color_bg3)]($style)'

[status]
disabled = false
symbol = "✘"
success_symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol $status ](fg:color_fg0 bg:color_red)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:#a0a9cb bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
