#!/usr/bin/env bash

set -e

STATE="$HOME/.local/state/current-theme"

CURRENT=$(cat "$STATE" 2>/dev/null || echo graphite)

case "$CURRENT" in
    graphite)
        theme-vintage
        ;;
    vintage)
        theme-jade
        ;;
    jade)
        theme-graphite
        ;;
    *)
        theme-graphite
        ;;
esac
